I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 2, in script
    define c = Character("Clara", callback=clara_voice) #50/50 clovek, hodna nebo zla
  File "game/script.rpy", line 2, in <module>
    define c = Character("Clara", callback=clara_voice) #50/50 clovek, hodna nebo zla
NameError: name 'clara_voice' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 2, in script
    define c = Character("Clara", callback=clara_voice) #50/50 clovek, hodna nebo zla
  File "C:\Users\Klara\Desktop\renpy-8.3.0-sdk\renpy\ast.py", line 2234, in execute
    self.set()
  File "C:\Users\Klara\Desktop\renpy-8.3.0-sdk\renpy\ast.py", line 2248, in set
    value = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "C:\Users\Klara\Desktop\renpy-8.3.0-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 2, in <module>
    define c = Character("Clara", callback=clara_voice) #50/50 clovek, hodna nebo zla
NameError: name 'clara_voice' is not defined

Windows-10-10.0.22631 
Ren'Py 8.3.0.24082114
renpy_yeehaw 1.0
Fri Sep  6 17:57:35 2024
